// A minimal OpenAI-compatible chat completions API for the end-to-end tests:
// users add it as a custom AI endpoint (http://fake-llm:8080/v1) and the API
// runs its AI features on it. It answers with fixed, valid content and
// rejects the key "rejected-key" like a provider would.
import { createServer } from 'node:http';

const trainingEvent = {
  type: 'TRAINING',
  name: 'Easy endurance run',
  description: 'Easy aerobic run generated by the fake LLM',
  sport: 'RUNNING',
  startDate: '2026-10-05T08:00:00.000Z',
  endDate: '2026-10-05T08:45:00.000Z',
  goalDuration: 2700,
  workout: {
    steps: [
      {
        stepType: 'STEADY',
        name: 'Easy run',
        durationType: 'TIME',
        durationValue: 2700,
      },
    ],
  },
};

function answerFor(messages) {
  const text = JSON.stringify(messages);
  if (text.includes('extractedRpe')) return { extractedRpe: 0.6 };
  if (text.includes('"injuries"')) return { injuries: [] };
  if (text.includes('questions')) {
    return { questions: [{ text: 'How did your legs feel?' }] };
  }
  if (text.includes('workout')) return trainingEvent;
  return 'OK';
}

function send(response, status, body) {
  response.writeHead(status, { 'content-type': 'application/json' });
  response.end(JSON.stringify(body));
}

createServer((request, response) => {
  let raw = '';
  request.on('data', (chunk) => (raw += chunk));
  request.on('end', () => {
    if (request.url === '/health') return send(response, 200, { ok: true });
    if (!request.url?.endsWith('/chat/completions')) {
      return send(response, 404, { error: { message: 'Not found' } });
    }
    if (request.headers.authorization === 'Bearer rejected-key') {
      return send(response, 401, { error: { message: 'Invalid API key' } });
    }
    const body = JSON.parse(raw || '{}');
    const answer = answerFor(body.messages ?? []);
    send(response, 200, {
      id: 'chatcmpl-e2e',
      object: 'chat.completion',
      created: Math.floor(Date.now() / 1000),
      model: body.model,
      choices: [
        {
          index: 0,
          message: {
            role: 'assistant',
            content: typeof answer === 'string' ? answer : JSON.stringify(answer),
          },
          finish_reason: 'stop',
        },
      ],
      usage: { prompt_tokens: 10, completion_tokens: 10, total_tokens: 20 },
    });
  });
}).listen(8080);
